pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
	PATH = 'C:/WINDOWS/SYSTEM32'
 }
 stages {
 	stage ('Build'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -f mockhttprequest/pom.xml clean install'
 			}
 		}
 	}
	stage('SonarQube Analysis'){
		steps {
			withSonarQubeEnv('SonarQube'){
				bat 'mvn clean install sonar:sonar'
			}
		}
    }
 	stage ('Deploy'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -f mockhttprequest/pom.xml deploy -Dusername=vij4m3 -Dpassword=Ted@123 -Denvironment=Sandbox -Dcloudhub.worker.type=Micro -DmuleDeploy'
 			}
 		}
 	}
 }

}
