#http
http:
  port: "8081"

#Mysql Configuration
db:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "javaj2ee"
  schema: "prod_db"
  
#oauth configuration
oauth:
  host: "mule3-oauth2-provider.us-e2.cloudhub.io"
  path: "/access_token"