pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
	PATH = 'C:/WINDOWS/SYSTEM32'
 }
 stages {
    stage('Unit Test') {
      steps {
      	withMaven(maven:'maven'){
       		bat 'mvn -f mockhttprequest/pom.xml clean test'
      	}
      }
    }
 	stage ('Deploy CloudHub'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn deploy -f mockhttprequest/pom.xml -P cloudhub  -Dusername=vij4m3 -Dpassword=Ted@123'
 			}
 		}
 	}
 }

}