pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
	PATH = 'C:/WINDOWS/SYSTEM32'
 }
 stages {
 	stage ('Build'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -f mule-oauth2-provider/pom.xml clean install'
 			}
 		}
 	}
 	stage ('Deploy'){
 		steps {
 			withMaven(maven:'maven'){
 				bat 'mvn -f mule-oauth2-provider/pom.xml package deploy  -Dusername=vij4m3 -Dpassword=Ted@123 -Denv=Sandbox -DmuleDeploy'
 			}
 		}
 	}
 }

}