pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
	PATH = 'C:/WINDOWS/SYSTEM32'
 }
 stages {
    stage('Unit Test') {
      steps {
        sh 'mvn clean test'
      }
    }
 	stage ('Deploy CloudHub'){
 		steps {
 				bat '- mvn deploy -P cloudhub  -Dusername=vij4m3 -Dpassword=Ted@123'
 		}
 	}
 }

}