pipeline{
agent any
tools {
    nodejs 'NodeJS'
  }
 stages {
  stage('Build Angular App') {
    steps {
      bat 'npm install'
    }
  }
    stage('Sonar Analyse') {
      steps {
        script  {
                def scannerHome = tool 'SonarQubeScanner';
                withSonarQubeEnv('SonarQube') {
                  bat "${scannerHome}/bin/sonar-scanner"
                }
               }
              } 
            }
 }
}
