pipeline {
agent any
environment {
  scannerHome = tool 'SonarQubeScanner'
}
stages {
    stage('Sonar Analyse') {
      steps {
                withSonarQubeEnv('SonarQube') {
                  bat "${scannerHome}/bin/sonar-scanner"
                }
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
              }
            }
        }
    }
}
